experiment:
  name: gns_optuna
  description: Optimization configuration for GNS model
  version: 1.0
  tags: [optuna, nlr7301]
  seed: 42  # Global seed for reproducibility

resources:
  graph_path: /home/p.yeste/CETACEO_DATA/nlr7301/TRAIN_converter.h5

optuna:
  study:
    study_name: "gns_optuna_search"
    direction: minimize
    save_path: "./results/optuna/"
    storage: null
    load_if_exists: true
    timeout: 3600
    n_trials: 50

    pruner:
      type: MedianPruner
      n_startup_trials: 5
      n_warmup_steps: 10
      interval_steps: 1

    sampler:
      type: TPESampler
      multivariate: true
      group: true
      seed: 42  # Optionally override experiment.seed

  search_space:
    model:
      latent_dim: [8, 64]
      hidden_size: [64, 512]
      num_msg_passing_layers: [1, 6]
      encoder_hidden_layers: [1, 4]
      decoder_hidden_layers: [1, 4]
      message_hidden_layers: [1, 4]
      update_hidden_layers: [1, 4]
      activation: ELU
      p_dropouts: [0.0, 0.3]
      device: cuda

    training:
      lr: [1e-5, 1e-2]
      lr_gamma: [0.95, 0.999]
      batch_size: [4, 32]
      node_batch_size: [128, 2048]
