run_config:

  basedir: "./data/NLR7301"
  results_dir: "./results/exp_01"

  mode: train                     # Options: train, optuna
  resume: false               # Optional: resume from checkpoint  

  train_config: "./configs/train_config.yaml"
  optuna_config: "./configs/optuna_config.yaml"

  tags: [baseline, nlr7301]

  evaluation:
    plot_true_vs_pred: true
    plot_train_test_loss: true
    save_model: true
    save_metrics: true
    model_path: "gns_model.pth"
    metrics_path: "metrics.json"

  logging:
    level: INFO
    logfile: null
