model:
  input_dim: 2
  output_dim: 1
  latent_dim: 16
  hidden_size: 256
  num_msg_passing_layers: 3
  encoder_hidden_layers: 2
  decoder_hidden_layers: 1
  message_hidden_layers: 2
  update_hidden_layers: 2
  activation: ELU                # Can be resolved to torch.nn.ELU()
  p_dropouts: 0.1
  device: cuda                   # or "cpu"

training:
  epochs: 1000
  lr: 6e-4
  lr_gamma: 0.995
  lr_scheduler_step: 1
  loss_fn: MSELoss               # Can be resolved to torch.nn.MSELoss
  optimizer: Adam                # Can be resolved to torch.optim.Adam
  scheduler: StepLR              # Can be resolved to torch.optim.lr_scheduler.StepLR
  batch_size: 16
  node_batch_size: 256
  num_workers: 1
  pin_memory: true
  seed: 123
  verbose: 50